### ISSUE TITLE
Error When I join The Server

### ISSUE THREAD

**Issue by zikehalil3535** [SkinsRestorer/SkinsRestorer#1691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

![image](https://github.com/user-attachments/assets/56f969a2-2bb8-49a4-b045-79024ff7a090)

### How can we reproduce what you got?

When I join the server I get this error.

### Minecraft implementation

```markdown
- Proxy: Velocity Latest
- Backend: Purpur 1.20.6 Latest
```

### What client are you using?

PrismLauncher 1.20.6

### SkinsRestorer Version

Latest

### List of plugins

Skinsrestorer

### Java Version

Temurin-21.0.3+9 (build 21.0.0.+9-LTS)

### Does your issue require a plugin in order to reproduce?

No

**Comment by AlexProgrammerDE** [comment]
Fixed with 15.3.0.
