### ISSUE TITLE
OPEN_GUI api on bukkit side

### ISSUE THREAD

**Issue by GWServer** [SkinsRestorer/SkinsRestorer#271]
I ask you to do the launch of the team / skin via bungee through the plugin channel  SkinsRestorer.
I want to install this command on NPC
Thank

**Comment by xknat** [comment]
cant use message channel? https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/

Edit: plugin workaround --> https://www.spigotmc.org/resources/commandforward.27580/

**Comment by sergservis** [comment]
I can. But all I would like SkinsRestorer to know how to wish it
:)

**Comment by xknat** [comment]
@sergservis a command seems unlikely.
is a api hook okey?

**Comment by sergservis** [comment]
okey?

**Comment by xknat** [comment]
Just execute the command as player...
