### ISSUE TITLE
Add cooldown to storage

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorer#317]
- [ ] replace hashmap with file (save cooldown)
- [ ] rewrite cooldown checker to check in the file
optional:
- [ ] Option for cooldown to be applied on new member.

**Comment by baticag** [comment]
Any news about this?

**Comment by baticag** [comment]
Any news about this?

**Comment by xknat** [comment]
Still planned, cooldown is currently working great, while there are some other things that need immediately be fixed / improved.

**Comment by AlexProgrammerDE** [comment]
Do people really need this? Imo it's kind of unnecessary... Do servers really have that long cooldowns? If they have like daily cooldowns maybe they should consider using permissions instead.

**Comment by xknat** [comment]
> Do people really need this? Imo it's kind of unnecessary... Do servers really have that long cooldowns? If they have like daily cooldowns maybe they should consider using permissions instead.

Yes, some servers have 1x a day skin they allow and smach premium towards removing cooldown

**Comment by baticag** [comment]
Any news about this?

**Comment by AlexProgrammerDE** [comment]
Done
