### ISSUE TITLE
gui skin filter include space in between filter

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorer#331]
**DEV: keep (multiple) space in front string in mind!**

Apply new filter here:
https://github.com/SkinsRestorer/SkinsRestorerX/blob/b3af781c73630cfbc1278517d561eee1c6b50640/src/main/java/skinsrestorer/shared/storage/SkinStorage.java#L457

https://github.com/SkinsRestorer/SkinsRestorerX/blob/b3af781c73630cfbc1278517d561eee1c6b50640/src/main/java/skinsrestorer/shared/storage/SkinStorage.java#L516

examples:
regex (\s|^) etc to exclude first space but should be multiple first white space before start of non space.

**Comment by AlexProgrammerDE** [comment]
should not be an issue anymore
