### ISSUE TITLE
File integrity isn't checked when update downloaded

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [SkinsRestorer/SkinsRestorer#372]
# Server Information #
Newest BungeeCord and paper
All paper servers and BungeeCord server are using the newest release of SkinsRestorer
### **The server is in China and we cannot connect to GitHub very smoothly**

# Bug #
The downloaded update files are broken(BECAUSE THE SERVER IS IN CHINA) and we cannot turn off the update option. #371 
Every time the plugin updated and we restart the server, the plugin jar file will be replaced by the broken jar and the server cannot load it. We must replace the jar manually every time the SkinsRestorer updated.

Can you add a hash check for the downloaded jar file or add a switcher for auto update?

**Comment by AlexProgrammerDE** [comment]
Will require a website API, but it's doable. There is no good way to do this with github since they don't provide hashes.

**Comment by AlexProgrammerDE** [comment]
Fixed by https://github.com/SkinsRestorer/SkinsRestorer/commit/0102d41cf9f42d970eb79269b7f4be39f17447b9
