### ISSUE TITLE
make updater retry on http 404 error.

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorer#556]

**Comment by AlexProgrammerDE** [comment]
Does that happen usually?

**Comment by xknat** [comment]
> Does that happen usually?

GitHub has a API limit, if you are a shared host you can get rate limited

**Comment by AlexProgrammerDE** [comment]
But why a 404? That usually means not found.

**Comment by xknat** [comment]
> But why a 404? That usually means not found.

oh ehm, i think firewall stuff
ppl allowing not github api, no clue. i think what i did mean was try again on not being able to request / download
