### ISSUE TITLE
can you please add cooldown for different groups different cooldown

### ISSUE THREAD

**Issue by MoGGaming** [SkinsRestorer/SkinsRestorer#663]
Like group A can change there skin in 1 day
group B can change there skin in every 3 days
it will be better if it  possible

**Comment by xknat** [comment]
We fear that this might be abused as a premium feature.
We want skinsrestorer to restore skins for everyone, and we would not like to be put behind a paywall.

**Comment by xknat** [comment]
Yeah, no go, modify the plugin.
